### PR TITLE
feat: Add `OpenSearch Dashboard` service on develop stack.

### PR DESCRIPTION
**Pull request by EdwinBetanc0urt**
- Add `OpenSearch Dashboard` service.
- Update `OpenSearch` from `2.11.1` to `2.13.0`

### CODE REVIEW

**Comment by marcalwestf** [comment]
hi @EdwinBetanc0urt  one question: are you still adding the _OpenSearch Dashboard_ service as a separate file and including it on file **start-all.sh** for the _develop_ stack?

Otherwise, we would get a discrepancy between "legacy" and the actual solution with separate services.

Thanks!

**Comment by EdwinBetanc0urt** [comment]
Thanks for the observation @marcalwestf, I had overlooked it. I already made a commit adding the separate service in the `19a-opensearch_dashboards_service_with_port.yml` file and integrating it only when running: `bash start-all.sh -d develop` and `bash start-all.sh -d develop -l`.

imagen

**Comment by marcalwestf** [comment]
Hi @EdwinBetanc0urt 

There is only a couple of small changes in file **start-all.sh** to be complete:

1.- Define the new service _Opensearch Dashboards_ and its index:
`OPENSEARCH_DASHBOARDS=18`

2.- Include the new service  _Opensearch Dashboards_ at the end  in the services array so it is at the correct position:
`SERVICES_ordered_array=(POSTGRESQL_SERVICE S3_STORAGE S3_CLIENT S3_GATEWAY_RS ADEMPIERE_SITE ADEMPIERE_ZK ADEMPIERE_PROCESSOR DKRON_SCHEDULER ADEMPIERE_GRPC_SERVER GRPC_PROXY VUE_UI ZOOKEEPER KAFKA OPENSEARCH_NODE OPENSEARCH_SETUP OPENSEARCH_GATEWAY_RS UI_GATEWAY KEYCLOAK OPENSEARCH_DASHBOARDS)`

3.- Include the service  _Opensearch Dashboards_ in the develop array at the correct index:
```
# Services for DEVELOP
declare -a DEVELOP_array
DEVELOP_array[$POSTGRESQL_SERVICE]="01a-postgres_service_with_ports.yml"
DEVELOP_array[$S3_STORAGE]="02a-s3_storage_service.yml"
DEVELOP_array[$S3_CLIENT]="03a-s3_client_service.yml"
DEVELOP_array[$S3_GATEWAY_RS]="04a-s3_gateway_rs_service_develop.yml"
DEVELOP_array[$ADEMPIERE_SITE]="05a-adempiere_site_service.yml"
DEVELOP_array[$ADEMPIERE_ZK]="06a-adempiere_zk_service.yml"
DEVELOP_array[$ADEMPIERE_PROCESSOR]="07a-adempiere_processor_service.yml"
DEVELOP_array[$DKRON_SCHEDULER]="08a-dkron_scheduler_service.yml"
DEVELOP_array[$ADEMPIERE_GRPC_SERVER]="09a-adempiere_grpc_server_service.yml"
DEVELOP_array[$GRPC_PROXY]="10b-grpc_proxy_service_develop.yml"
DEVELOP_array[$VUE_UI]="11a-vue_ui_service.yml"
DEVELOP_array[$ZOOKEEPER]="12a-zookeeper_service.yml"
DEVELOP_array[$KAFKA]="13a-kafka_service.yml"
DEVELOP_array[$OPENSEARCH_NODE]="14a-opensearch_node_service_with_port.yml"
DEVELOP_array[$OPENSEARCH_SETUP]="15a-opensearch_setup_service.yml"
DEVELOP_array[$OPENSEARCH_GATEWAY_RS]="16c-opensearch_gateway_rs_service_develop.yml"
DEVELOP_array[$UI_GATEWAY]="17c-ui_gateway_service_develop.yml"
DEVELOP_array[$KEYCLOAK]="18a-keycloak_service.yml"
DEVELOP_array[$OPENSEARCH_DASHBOARDS]="19a-opensearch_dashboards_service_with_port.yml"


Otherwise, you would have overwriten KEYCLOAK.

Thanks!
```

**Comment by EdwinBetanc0urt** [comment]
Hello @marcalwestf , I already uploaded the correction with adding the new service with its index, adding it to the array and changing the index with the file name

**Review by marcalwestf — APPROVED** [review]
Changes OK

**Pull request merged**
