### PR TITLE
feat: Change service names, separator `.` to `-`.

### PR DESCRIPTION
**Pull request by EdwinBetanc0urt**
In some services it is necessary to put the ip of the server when placing it in the Application Registry because it does not resolve correctly the name of the service, this because it tries to resolve a domain name when it contains dots as word separator.

Now they are changed to contain hyphen separator, in the same way that kubernetes handles it.

imagen

imagen

### CODE REVIEW

**Comment by marcalwestf** [comment]
@EdwinBetanc0urt  nice step to standardize names of containers and services. 

Tough I haven't encountered such an error, I know the dot character is used for domain separation.

Start testing now.

**Review by marcalwestf — COMMENTED** [review]
I started checking the files.

There are a couple of differences between files  env_template.env and .env:
Selection_014

Selection_015

I suppose both files should be identical.

**Comment by marcalwestf** [comment]
Just checked the diffs of the files.
Everything is OK.

Waiting for the changes in .env and env_template.env to finish the test.

**Comment by EdwinBetanc0urt** [comment]
@marcalwestf Thanks, I didn't notice the difference, I left both files the same.

**Comment by marcalwestf** [comment]
Testing with the following command:
`./start-all.sh`

The file docker-compose.yml is generated for the "standard" stack and the immages are pulled:
image

After images are pulled, containers are instantiated:
Selection_016

The error message is
`dependency failed to start: container adempiere-ui-gateway.envoy-grpc-proxy exited (1)`

Running `docker compose convert`, the values seem ok.


`docker compose ps -a` delivers several exited services.
image

The exited services are:
- adempiere-ui-gateway.envoy-grpc-proxy
- adempiere-ui-gateway.opensearch-setup
- adempiere-ui-gateway.s3-client

**Comment by marcalwestf** [comment]
... but if on the other side, I start  the same, but using the legacy flie
`./start-all.sh -l`

everything works OK:
image

It seems to be a discrepancy between the files that convert the standard stack and the legacy file.

I will check both `docker compose convert` results.

**Comment by marcalwestf** [comment]
When issuing `docker compose convert`  for `./start-all.sh` and `./start-all.sh -l` and comparing the results, there are some differences:

image
image
image
image
image
image

These differences are the cause of the error.

Perhaps there are more discrepancies that must be leveled.

**Comment by marcalwestf** [comment]
hi @EdwinBetanc0urt  I fetched the latest changes and tested.
Here are my results:

**I Run the script with the legacy file**
`./start-all.sh -l`
Result: services seem to have been created, are started and healthy
image

**II Test Web UI**
ZK works:
image


**III Inspect the containers with docker**
Run  `docker compose ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Service}}"`

Result:
CONTAINER ID   <no value>                              STATUS                   SERVICE
ec1a04a21d0b   adempiere-ui-gateway.opensearch-setup&nbsp;&nbsp;&nbsp;&nbsp;Exited (0) 7 hours ago   opensearch-setup
c238ec3d6b9c   adempiere-ui-gateway.s3-client&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Exited (0) 7 hours ago   s3-client

a863e0dbe9ad   adempiere-ui-gateway.dictionary-rs      Up 7 hours (healthy)     dictionary-rs
e993dae6c571   adempiere-ui-gateway.envoy-grpc-proxy   Up 7 hours (healthy)     grpc-proxy
aac01b51012b   adempiere-ui-gateway.kafka              Up 7 hours (healthy)     kafka
9eaf7e2e6452   adempiere-ui-gateway.nginx-ui-gateway   Up 7 hours               ui-gateway
b98c05aa8365   adempiere-ui-gateway.opensearch         Up 7 hours (healthy)     opensearch-node
1528ae0ef382   adempiere-ui-gateway.postgresql         Up 7 hours (healthy)     postgresql-service
98d25bb1ef2a   adempiere-ui-gateway.processor          Up 7 hours (healthy)     adempiere-processor
522d5f9a0141   adempiere-ui-gateway.report-engine      Up 7 hours (healthy)     adempiere-report-engine
4c8b718f723a   adempiere-ui-gateway.s3-gateway-rs      Up 7 hours (healthy)     s3-gateway-rs
6ffd0c209650   adempiere-ui-gateway.s3-storage         Up 7 hours (healthy)     s3-storage
7c2e49baa8b1   adempiere-ui-gateway.scheduler-dkron    Up 7 hours               dkron-scheduler
f9ad79578eaa   adempiere-ui-gateway.site               Up 7 hours               adempiere-site
eea8c8bf11d8   adempiere-ui-gateway.vue-grpc-server    Up 7 hours (healthy)     adempiere-grpc-server
871ad5297957   adempiere-ui-gateway.vue-ui             Up 7 hours               vue-ui
c780fe24524b   adempiere-ui-gateway.zk                 Up 7 hours               adempiere-zk
d52d91bf03db   adempiere-ui-gateway.zookeeper          Up 7 hours (healthy)     zookeeper


All services but **opensearch-setup** and **s3-client** -which have exited- seem to be working OK

**IV Inspect log of exited containers**
Find the log file with 
`docker inspect adempiere-ui-gateway.s3-client`

Contents of log file:
```
{"log":"Added `s3_minio_server` successfully.\n","stream":"stdout","time":"2024-08-26T12:13:18.955175874Z"}
{"log":"mc: \u003cERROR\u003e Unable to make bucket `s3_minio_server/adempiere`. Your previous request to create the named bucket succeeded and you already own it.\n","stream":"stderr","time":"2024-08-26T12:13:18.993487383Z"}
```

(The opensearch-setup log stated that the index must be run again)

**Comment by marcalwestf** [comment]
@EdwinBetanc0urt  I suppose the exiting services are due to other reasons than the present pull request.

Is it so?
The error of service _opensearch-setup_ might be tackled with running the services again, but I am not sure what is needed for service _s3-client_.

**Comment by EdwinBetanc0urt** [comment]
@marcalwestf 
The `opensearch-setup` and `s3-client` services are services that are run only to set up an initial configuration and stop.

`s3-client`:
- Creates a `secret key` with value `adempiere`.
- Creates an `access key` with value `adempiere`.
- Create a `bucket` with name `adempiere`.

This so that it has the same connection values created in the database with the `App Registration` to external file handler.

`opensearch-setup`:
- Disables the disk allocation decider. This will also remove any existing `index.blocks.read_only_allow_delete` index blocks when disabled.
- Disables the disk allocation decider. This will also remove any existing index.blocks.read_only_allow_delete index blocks when disabled.
- Create a repository which is nothing more than a path (which has a shared volume with `docker-compose/opensearch/snapshots`) and type of filesystem where snapshots will be made (equivalent to backups) called `default-repository`.
- Restore the snapshot located in `docker-compose/opensearch/snapshots` linked to the `default-repository`, so that OpenSearch has the `indexes` (equivalent to sql database tables) and its `documents` (equivalent to sql database records).


image

image

**Comment by marcalwestf** [comment]
@EdwinBetanc0urt  thanks for the clarification Edwin.
As is was already tested several weeks ago, I will proceed to accept it.

**Review by marcalwestf — APPROVED** [review]
after testing and clarifications, PR accepted

**Pull request merged**
