### PR TITLE
docs: Cache Diagram

### PR DESCRIPTION
**Pull request by Ricargame**
image

### CODE REVIEW

**Comment by marcalwestf** [comment]
@Ricargame : the image  looks god.
I would suggest that you insert it in the README.md file, so it can be seen by everybody.
Thanks!!!

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]
The background of the diagram is dark, please make it white or transparent.

**Comment by Ricargame** [comment]
hi @marcalwestf This is a chapter of how the diagram turned out.  
image

**Review by EdwinBetanc0urt — APPROVED** [review]

**Comment by yamelsenih** [comment]
> image

Hello, the Nginx layer should be a specific layer named gateway

**Pull request merged**
