### PR TITLE
Add kafdrop service to new kafka service file

### LINKED ISSUE #74: Add Kafdrop to Kafka
Kafdrop (https://github.com/obsidiandynamics/kafdrop) is a tool to administer topics, partitions, records, user groups, etc. in Kafka.

Though it is not recommended to use it in a production stack, it may be of great help when testing or debugging.

In our case, it would be added to the "develop" stack.

### PR DESCRIPTION
**Pull request by marcalwestf**
Fixes https://github.com/adempiere/adempiere-ui-gateway/issues/74

An additional file was added, where the Kafdrop service is added to the Kafka service.

This file is used only for the "Develop" stack.

This pull Request is not to be merged yet, because of the problems explained at https://github.com/adempiere/adempiere-ui-gateway/issues/74#issuecomment-2050747010

@EdwinBetanc0urt  can you have a look, please?
Thanks!

### CODE REVIEW

**Comment by EdwinBetanc0urt** [comment]
Hi @marcalwestf, i test your changes, for it to work the port must be the internal port of kafka as it communicates within the docker network in this case `9092`.

imagen


The topic was created by exporting only the dictionary definition of the `SmartBrowse`.


A suggestion is not to use the latest version, but specify the version, because today your latest is the `sha256:e71b1cc1dd25` if tomorrow they publish another version, change the sha256 and on my machine or server may be another version different from yours, this way we ensure that it is always the same version that we all handle.

imagen



```yml
  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    ports:
      - 19000:9000  # 9000 collides with s3.storage
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - adempiere_network
```

**Comment by marcalwestf** [comment]
@EdwinBetanc0urt , @yamelsenih  implementing Edwin's suggestions, Kafdrop can now manage the Kafka objects just by opening a browser and typing in:
- `http://0.0.0.0:19000/`
- `http://localhost:19000/`
- `http://<HOST IP>:19000/`
- `http://api.adempiere.io:19000/`
- `http://<KAFDROP CONTAINER IP>:9000`
- `http://<CONTAINER NETWORK IP>:9000`

This means:
- all IPs **outside** the Container Network have to use Port **19000**
  This includes the host.
- all IPs **inside** the Container Network have to use Port **9000**

**Comment by EdwinBetanc0urt** [comment]
It looks good only request is that you could add it to the `docker-compose-develop.yml` file.

**Comment by marcalwestf** [comment]
oops!!! Almost forgot it!!!

I will do  it right now.

**Review by EdwinBetanc0urt — APPROVED** [review]
Run with legacy `docker compose`:
```bash
docker compose --env-file env_template.env -f docker-compose-develop.yml up
```


imagen


And run with bash script
```bash 
./start-all.sh -d develop
```

imagen


This is working correctly:

imagen

**Comment by marcalwestf** [comment]
Great @EdwinBetanc0urt !

FYI: you can use the start-all.sh script for legacy, too.

Just type in -l for legacy and you run the stack on legacy:
`./start-all.sh -d develop -l`

**Pull request merged**
