### PR TITLE
Bugfix/dkron browser access

### LINKED ISSUE #86: Dkron is not displayed in browsers
As of now, the dkron is not displayed on browsers.
In the definition of the dkron service, no ports are defined, i.e. the defaults are taken.

## Test # 1 
**Result: 
When the tests are done with the present parameters, the browser is only displayed if we use the Container IP and the port 8080**

- http://0.0.0.0:8899/dashboard  &ensp; &ensp; Firefox can’t establish a connection to the server at 0.0.0.0:8899.
- http://0.0.0.0:8899   &ensp; &ensp;  Firefox can’t establish a connection to the server at 0.0.0.0:8899.
- http://0.0.0.0:8899/ui  &ensp; &ensp; status	502  message	"Bad gateway"
___ 
- http://0.0.0.0:8080/dashboard/ &ensp; &ensp; Firefox can’t establish a connection to the server at 0.0.0.0:8080.
- http://0.0.0.0:8080 &ensp; &ensp; Firefox can’t establish a connection to the server at 0.0.0.0:8080.
- http://0.0.0.0:8080/ui &ensp; &ensp; Firefox can’t establish a connection to the server at 0.0.0.0:8080        
___  
- http:// CONTAINER IP:8899/dashboard/ &ensp; &ensp; Firefox can’t establish a connection to the server at 192.168.100.4:8899.
- http:// CONTAINER IP:8899 &ensp; &ensp; Firefox can’t establish a connection to the server at 192.168.100.4:8899
- http:// CONTAINER IP/ui  &ensp; &ensp; An error occurred during a connection to 192.168.100.4
- http:// CONTAINER IP:8899/ui &ensp; &ensp;  Firefox can’t establish a connection to the server at 192.168.100.4:8899
___
- http:// CONTAINER IP:8080/dashboard/ &ensp; &ensp; 404 page not found
- http:// CONTAINER IP:8080 &ensp; &ensp; **The dkron page is displayed on the browser!!!!**
- http:// CONTAINER IP:8080/ui  &ensp; &ensp; **The dkron page is displayed on the browser!!!!**
___
- http:// HOST IP:8899/ui/ &ensp; &ensp; Firefox can’t establish a connection to the server at 192.168.1.6:8899
- http://api.adempiere.io:8899 &ensp; &ensp; Firefox can’t establish a connection to the server at api.adempiere.io:8899
- http://localhost:8899 &ensp; &ensp;  Firefox can’t establish a connection to the server at localhost:8899:

### PR DESCRIPTION
**Pull request by marcalwestf**
Fixes: https://github.com/adempiere/adempiere-ui-gateway/issues/86

Without the changes, one must run a docker inspect, fiind out the container IP and then run it on a browser:
`docker inspect adempiere-ui-gateway.scheduler.dkron | less`
```

            "Networks": {
                "adempiere-ui-gateway.network": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "adempiere-ui-gateway.scheduler.dkron",
                        "dkron.scheduler",
                        "056e2ab9f700",
                        "adempiere-ui.dkron"
                    ],
                    "NetworkID": "ee9784d01630918c59cfd83bbd87819780dba9461129bf9aa26af08e5e6efcd0",
                    "EndpointID": "a79e081fde4133f755e31c99f7fc0cfa27da3346cd2f0dc677b7e635fde11ad8",
                    "Gateway": "192.168.100.1",
                    "IPAddress": "192.168.100.6",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",

```
On the browser: `http://192.168.100.6:8080/ui`
This is not practical.

With  the changes suggested, the dkron is displayed on the browser using either of the following:
- http://0.0.0.0:8899 or http://0.0.0.0:8899/ui
- http:// CONTAINER IP:8080 or http:// CONTAINER IP:8080/ui
- http:// HOST IP:8899/ui 
- http://api.adempiere.io:8899
- http://localhost:8899

This means, dkron can be displayed with one of these IPs, which is more practical than hitherto.

image

### CODE REVIEW

**Comment by marcalwestf** [comment]
@EdwinBetanc0urt  you might have a look.
It should work with and without legacy.

Thanks!!!

**Comment by marcalwestf** [comment]
Additionally to this PR, the service  _adempiere.site_ should be updated so that the dkron service is called correctly from the landing page.

Right now, it is called as follows:
`http://api.adempiere.io/ui`

The correct way should be
`http://api.adempiere.io:8899/ui`

**Comment by marcalwestf** [comment]
**As I am unable to post an issue in https://github.com/adempiere/adempiere-landing-page , I describe the error and the solution I picture here:**

In  the [adempiere-ui-gateway repository](https://github.com/adempiere/adempiere-ui-gateway), the main page points to
```
# Main Page
ADEMPIERE_SITE_IMAGE="openls/adempiere-landing-page:alpine-1.0.3"
```

Unfortunately, when clicking on the Scheduler button on the main page
image

The result is an error:
Selection_446

The reason: 
- the external/internal ports were not defined correctly
- the button points to `http://api.adempiere.io/ui`

In the [pull request enabling dkron browser access](https://github.com/adempiere/adempiere-ui-gateway/pull/87), this error is solved. Once accepted, the files [main/src/README.md](https://github.com/adempiere/adempiere-landing-page/blob/main/src/README.md?plain=1) and [main/src/es/README.md](https://github.com/adempiere/adempiere-landing-page/blob/main/src/es/README.md?plain=1) must be changed accordingly.

**Comment by EdwinBetanc0urt** [comment]
Certainly the internal port is not the correct one in case of port forwarding it will give an error like the one shown, however it is easily corrected by setting the correct port `8080` in the upstream of the scheculer.

Proposed changes to your branch https://github.com/Systemhaus-Westfalia/adempiere-ui-gateway/pull/1 for you to integrate with this change, add the dkron agent port

**Pull request merged**
